# Generated by Django 2.2.10 on 2020-03-10 14:22

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_supplier', models.BooleanField(default=0)),
                ('is_customer', models.BooleanField(default=0)),
                ('is_agent', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('invoice_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=10)),
                ('invoice_value', models.FloatField()),
                ('commission', models.FloatField()),
                ('cash_discount', models.FloatField()),
                ('freight', models.FloatField()),
                ('insurance', models.FloatField()),
                ('gst', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('total_amount_payable', models.FloatField()),
                ('remarks', models.CharField(max_length=50)),
                ('additional_remark', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Bill/Invoice',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tag', models.CharField(choices=[('P', 'Personal'), ('W', 'Work'), ('T', 'Travel'), ('I', 'Important')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Calendar Events',
            },
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('is_favourite', models.BooleanField(default=0)),
                ('tag', models.CharField(choices=[('P', 'Personal'), ('W', 'Work'), ('S', 'Social'), ('I', 'Important')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('addr1', models.CharField(max_length=100)),
                ('addr2', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Responsible Offices',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_no', models.SlugField()),
                ('date_of_inquiry', models.DateField()),
                ('po_no', models.CharField(max_length=20)),
                ('contract_no', models.CharField(max_length=20)),
                ('price_kg', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('dispatch_qty', models.IntegerField()),
                ('contract_value', models.IntegerField()),
                ('quantity_discount', models.IntegerField()),
                ('insurance', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
                ('extra_remarks', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('financial_year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=0)),
                ('order_confirmation', models.CharField(max_length=4)),
                ('indenting_commission', models.IntegerField()),
                ('agent_commission', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agent.agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buyer.buyer')),
            ],
            options={
                'verbose_name_plural': 'Order Details',
            },
        ),
        migrations.CreateModel(
            name='product_shade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shade_name', models.CharField(max_length=50)),
                ('shade_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sub-Category 1',
            },
        ),
        migrations.CreateModel(
            name='subcategory2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sub-Category 2',
            },
        ),
        migrations.CreateModel(
            name='to_do',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('is_important', models.BooleanField(default=0)),
                ('is_completed', models.BooleanField(default=0)),
                ('is_deleted', models.BooleanField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "To Do's",
            },
        ),
        migrations.CreateModel(
            name='shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freight', models.FloatField()),
                ('dispatch_by', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('otif', models.BooleanField(default=0)),
                ('inco_terms', models.CharField(max_length=100)),
                ('place_of_delivery', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=50)),
                ('additional_remarks', models.TextField()),
                ('port_of_discharge', models.CharField(max_length=50)),
                ('courier_details', models.CharField(max_length=100)),
                ('email_date', models.DateField()),
                ('dispatch_summary_otif', models.BooleanField(default=0)),
                ('post_shipment_otif', models.BooleanField(default=0)),
                ('copy_of_shipment', models.BooleanField(default=0)),
                ('documents_otif', models.BooleanField(default=0)),
                ('status', models.CharField(choices=[('S', 'Shipped'), ('Di', 'Dispatch'), ('P', 'Pending'), ('Dl', 'Delivered')], max_length=4)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.order')),
            ],
            options={
                'verbose_name_plural': 'Shipment Details',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('application', models.CharField(max_length=50)),
                ('polymer_fiber', models.CharField(choices=[('P', 'Polyster'), ('F', 'fiber'), ('PA6', 'pa - 6'), ('Blnd', 'blend')], max_length=4, verbose_name='Polymer/Fiber')),
                ('luster', models.CharField(choices=[('sd', 'Semi Dull'), ('brt', 'Bright'), ('sbrt', 'superbrt')], max_length=4)),
                ('filament_cross_section', models.CharField(choices=[('C', 'Circular'), ('cir', 'cir'), ('tbl', 'tbl'), ('T', 'triangular')], max_length=4)),
                ('tex_specification', models.CharField(choices=[('210', '210mm'), ('z-t', 'z - twist'), ('na', 'Not Applicable')], max_length=4)),
                ('required_no_of_nips', models.CharField(choices=[('40-50', '40 - 50'), ('85-90', '85 - 90'), ('sim', 'sim'), ('na', 'Not Applicable')], max_length=4)),
                ('lycra_percent_or_any_additional_additive', models.CharField(max_length=4)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.category')),
                ('shade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.product_shade')),
                ('sub_category_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subcategory1')),
                ('sub_category_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subcategory2')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuurency', models.CharField(max_length=10)),
                ('payment_terms', models.CharField(max_length=100)),
                ('payment_due_date', models.DateField()),
                ('remarks', models.CharField(max_length=200)),
                ('additional_remarks', models.TextField()),
                ('payment_status', models.BooleanField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.bill')),
            ],
            options={
                'verbose_name_plural': 'Payment Details',
            },
        ),
    ]
