# Generated by Django 2.2 on 2020-04-16 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('buyer', '0002_auto_20200416_0953'),
        ('employee', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('agent', '0002_auto_20200416_0953'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_quotations',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='suplus_product',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='suplus_product',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.product'),
        ),
        migrations.AddField(
            model_name='suplus_product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.order'),
        ),
        migrations.AddField(
            model_name='samplerequestproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.product'),
        ),
        migrations.AddField(
            model_name='samplerequestproduct',
            name='sample_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.SampleRequest'),
        ),
        migrations.AddField(
            model_name='samplerequestfeedback',
            name='sample_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.SampleRequest'),
        ),
        migrations.AddField(
            model_name='samplerequestdispatch',
            name='sample_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.SampleRequest'),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.inquiry'),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='intermingle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.intermingle'),
        ),
        migrations.AddField(
            model_name='product',
            name='required_no_of_nips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.required_no_of_nips'),
        ),
        migrations.AddField(
            model_name='product',
            name='shade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.product_shade'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subcategory1'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subcategory2'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.bill'),
        ),
        migrations.AddField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agent.agent'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buyer.buyer'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_supplier', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='responsible_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.office'),
        ),
        migrations.AddField(
            model_name='order',
            name='suppliers_quotation',
            field=models.ManyToManyField(related_name='initial_suppliers', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry_update',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='inquiry_update',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.inquiry'),
        ),
        migrations.AddField(
            model_name='inquiry_product',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.inquiry'),
        ),
        migrations.AddField(
            model_name='inquiry_product',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.PaymentTerms'),
        ),
        migrations.AddField(
            model_name='inquiry_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.product'),
        ),
        migrations.AddField(
            model_name='inquiry_product',
            name='suppliers',
            field=models.ManyToManyField(to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closing_user', to='agent.agent'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buyer.buyer'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='confirming_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closing_user', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inquiry_user', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='forwarded_quotation',
            name='inquiry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.inquiry'),
        ),
        migrations.AddField(
            model_name='forwarded_quotation',
            name='quotations',
            field=models.ManyToManyField(to='core.supplier_quotations'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customersampleref',
            name='sample_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.SampleRequest'),
        ),
        migrations.AddField(
            model_name='bill',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.order'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
