# Generated by Django 2.2.10 on 2020-03-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order Details'},
        ),
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(to='core.product'),
        ),
    ]
