# Generated by Django 2.2.10 on 2020-03-11 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200310_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='intermingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Intermingle',
            },
        ),
        migrations.CreateModel(
            name='required_no_of_nips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Required No of Nips',
            },
        ),
        migrations.CreateModel(
            name='updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IU', 'Industry Updates'), ('TA', 'Technological Advancements'), ('IDT', 'International Duties and Trade'), ('PTA', 'Price Trend Analysis')], max_length=3)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Updates/News',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Enquiry Details'},
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='order',
            new_name='enquiry',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='order',
            new_name='enquiry',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tex_specification',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='remarks',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='filament_cross_section',
            field=models.CharField(choices=[('C', 'Circular'), ('TL', 'Trilobal'), ('TA', 'Triangular'), ('OL', 'Octalobal'), ('S', 'Star'), ('R', 'Rice'), ('O', 'Orange'), ('C', 'Coolmax')], max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='luster',
            field=models.CharField(choices=[('sd', 'Semi Dull'), ('brt', 'Bright'), ('fd', 'Full Dull')], max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='required_no_of_nips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.required_no_of_nips'),
        ),
        migrations.CreateModel(
            name='suplus_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_product', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.IntegerField()),
                ('price_unit', models.IntegerField()),
                ('office', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('supplier_mob', models.CharField(blank=True, max_length=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Suplus Product Details',
            },
        ),
        migrations.CreateModel(
            name='notisfications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Notisfications',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='intermingle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.intermingle'),
            preserve_default=False,
        ),
    ]
