# Generated by Django 2.2 on 2020-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200416_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry_product',
            name='qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='supplier_quotations',
            name='price_kg',
            field=models.FloatField(),
        ),
    ]
