# Generated by Django 2.2 on 2020-04-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200418_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry_product',
            name='colour',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry_product',
            name='instructions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry_product',
            name='lusture',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry_product',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
