# Generated by Django 2.2.10 on 2020-03-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200311_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notisfications',
            new_name='notifications',
        ),
    ]
