# Generated by Django 2.2.10 on 2020-03-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200312_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cuurency',
            new_name='currency',
        ),
    ]
