# Generated by Django 2.2 on 2020-04-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200423_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_quotations',
            name='inco',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
