# Generated by Django 2.2 on 2020-05-09 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_country_code'),
        ('core', '0005_supplier_quotations_inco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.inquiry')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='IndentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fob_price', models.PositiveSmallIntegerField()),
                ('commission', models.PositiveSmallIntegerField()),
                ('ex_factory_dispatch', models.CharField(max_length=100)),
                ('etd', models.DateField()),
                ('eta', models.DateField()),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Indent')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier_quotations')),
            ],
        ),
    ]
