# Generated by Django 2.2.10 on 2020-03-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_is_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='inquiry_no',
            new_name='enquiry_no',
        ),
    ]
