# Generated by Django 2.2.10 on 2020-03-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_agent_image'),
        ('employee', '0004_auto_20200311_2107'),
        ('supplier', '0004_remove_supplier_consignee'),
        ('buyer', '0004_auto_20200311_2107'),
        ('core', '0007_auto_20200317_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('M', 'Mail'), ('WC', 'WeChat'), ('WP', 'Whatsapp'), ('C', 'Call')], max_length=2)),
                ('status', models.CharField(choices=[('O', 'Open'), ('CM', 'Confirmed'), ('CD', 'Closed')], max_length=2)),
                ('close_choice', models.CharField(blank=True, choices=[('HP', 'Prices are High'), ('QS', 'Quality Not from nominated Supplier'), ('AF', 'Awaiting Feedback'), ('UD', 'Under Discussion or Development'), ('NO', 'Not Offered')], max_length=2, null=True)),
                ('remarks', models.TextField()),
                ('received_datetime', models.DateTimeField(auto_now_add=True)),
                ('reply_datetime', models.DateTimeField(blank=True, null=True)),
                ('received_quotation_datetime', models.DateTimeField(blank=True, null=True)),
                ('selected_quotation_datetime', models.DateTimeField(blank=True, null=True)),
                ('customer_feedback_datetime', models.DateTimeField(blank=True, null=True)),
                ('confirmation_datetime', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closing_user', to='agent.agent')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buyer.buyer')),
                ('confirming_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closing_user', to='employee.employee')),
                ('inquiry_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inquiry_user', to='employee.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='source',
        ),
        migrations.CreateModel(
            name='supplier_quotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField()),
                ('document', models.FileField(upload_to='')),
                ('remark', models.TextField()),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.inquiry')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='notified_suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.inquiry')),
                ('suppliers', models.ManyToManyField(to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='inquiry_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('remark', models.TextField()),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.inquiry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='forwarded_quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.inquiry')),
                ('quotations', models.ManyToManyField(to='core.supplier_quotations')),
            ],
        ),
        migrations.CreateModel(
            name='customer_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.inquiry')),
            ],
        ),
    ]
