# Generated by Django 2.2.10 on 2020-03-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200327_0418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_feedback',
            options={'verbose_name_plural': 'Inquiry Customer Feedback'},
        ),
        migrations.AlterModelOptions(
            name='forwarded_quotation',
            options={'verbose_name_plural': 'Inquiry Customer Forwarded Quotations'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'Inquiry Details'},
        ),
        migrations.AlterModelOptions(
            name='inquiry_product',
            options={'verbose_name_plural': 'Inquiry Products'},
        ),
        migrations.AlterModelOptions(
            name='notified_suppliers',
            options={'verbose_name_plural': 'Inquiry Notified Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='supplier_quotations',
            options={'verbose_name_plural': 'Inquiry Supplier Quotations'},
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('CM', 'Confirmed'), ('CD', 'Closed')], default='O', max_length=2),
        ),
        migrations.AlterField(
            model_name='inquiry_product',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.inquiry'),
        ),
        migrations.AlterField(
            model_name='inquiry_product',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier_quotations',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
