# Generated by Django 2.2.10 on 2020-03-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200328_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry_product',
            name='delivery_terms',
            field=models.CharField(default=1, max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry_product',
            name='destination_port',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry_product',
            name='inco_terms',
            field=models.CharField(default=1, max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry_product',
            name='packing_requirement',
            field=models.CharField(default=1, max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry_product',
            name='payment',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
