# Generated by Django 2.2.10 on 2020-03-28 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200329_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='inquiry_updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.inquiry')),
            ],
            options={
                'verbose_name_plural': 'Inquiry Customer Feedback',
            },
        ),
        migrations.RenameField(
            model_name='supplier_quotations',
            old_name='total_price',
            new_name='price_kg',
        ),
        migrations.RemoveField(
            model_name='supplier_quotations',
            name='document',
        ),
        migrations.RemoveField(
            model_name='supplier_quotations',
            name='remark',
        ),
        migrations.AddField(
            model_name='supplier_quotations',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.inquiry_product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='customer_feedback',
        ),
    ]
