# Generated by Django 2.2.10 on 2020-03-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200329_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='inquiry_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date_time', models.DateField(auto_now_add=True)),
                ('subject', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.inquiry')),
            ],
            options={
                'verbose_name_plural': 'Inquiry Customer Feedback',
            },
        ),
        migrations.DeleteModel(
            name='inquiry_updates',
        ),
    ]
