# Generated by Django 2.2.10 on 2020-03-29 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200311_2107'),
        ('core', '0013_auto_20200329_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry_update',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee'),
            preserve_default=False,
        ),
    ]
