# Generated by Django 2.2.10 on 2020-03-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_inquiry_update_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry_product',
            name='remark',
        ),
    ]
