# Generated by Django 2.2.10 on 2020-04-01 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_inquiry_product_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry_product',
            name='delivery_terms',
        ),
        migrations.AddField(
            model_name='inquiry_product',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
