# Generated by Django 2.2.10 on 2020-04-03 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_remove_supplier_consignee'),
        ('employee', '0004_auto_20200311_2107'),
        ('core', '0016_auto_20200401_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suplus_product',
            name='office',
        ),
        migrations.RemoveField(
            model_name='suplus_product',
            name='supplier_mob',
        ),
        migrations.AddField(
            model_name='suplus_product',
            name='document',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suplus_product',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suplus_product',
            name='location',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updates',
            name='date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suplus_product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier'),
        ),
        migrations.CreateModel(
            name='SampleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(choices=[('IQ', 'Inquiry'), ('BD', 'Business Development')], max_length=2)),
                ('receiving_date', models.DateField(auto_now_add=True)),
                ('sample_received_date', models.DateField(blank=True, null=True)),
                ('sample_sent_date', models.DateField(blank=True, null=True)),
                ('courier_details', models.CharField(blank=True, max_length=256, null=True)),
                ('cti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.inquiry')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier')),
            ],
        ),
    ]
