# Generated by Django 2.2.10 on 2020-04-05 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200405_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplerequestproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.product'),
            preserve_default=False,
        ),
    ]
