# Generated by Django 2.2.10 on 2020-04-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_samplerequestproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersampleref',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customersampleref',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
