# Generated by Django 2.2.10 on 2020-04-06 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200405_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplerequestproduct',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
