# Generated by Django 2.2.10 on 2020-04-07 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_samplerequestproduct_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplerequestdispatch',
            name='estimate_delivery',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='samplerequestfeedback',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='samplerequestfeedback',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='samplerequestfeedback',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
