# Generated by Django 2.2 on 2020-04-14 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_remove_supplier_consignee'),
        ('core', '0023_auto_20200409_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('days', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='inquiry_product',
            name='payment',
        ),
        migrations.AddField(
            model_name='inquiry_product',
            name='suppliers',
            field=models.ManyToManyField(to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='supplier_quotations',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.PaymentTerms'),
        ),
        migrations.DeleteModel(
            name='notified_suppliers',
        ),
        migrations.AddField(
            model_name='inquiry_product',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.PaymentTerms'),
        ),
    ]
