# Generated by Django 2.2 on 2020-04-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='country_code',
            field=models.CharField(default='91', max_length=3),
        ),
    ]
