# Generated by Django 2.2.10 on 2020-03-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Designation',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
