# Generated by Django 2.2.10 on 2020-03-11 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200311_2050'),
        ('employee', '0002_auto_20200310_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_officer', models.CharField(max_length=100)),
                ('inspection_officer_contact', models.CharField(max_length=15)),
                ('document', models.FileField(upload_to='')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.order')),
            ],
        ),
    ]
