# Generated by Django 2.2.10 on 2020-03-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200311_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_visit',
            options={'verbose_name_plural': 'Employee Notes (Visit Details)'},
        ),
        migrations.AlterModelOptions(
            name='inspection',
            options={'verbose_name_plural': 'Inspection Details'},
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_additional_remarks',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_confirmation',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_remarks',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
