# Generated by Django 2.2.10 on 2020-03-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Declined'), ('A', 'Approved')], default='P', max_length=1),
        ),
    ]
