# Generated by Django 2.2 on 2020-04-16 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('buyer_name', models.CharField(max_length=100)),
                ('addr1', models.CharField(max_length=100)),
                ('addr2', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('concerned_person_name', models.CharField(max_length=100)),
                ('concerned_person_mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Buyers',
            },
        ),
        migrations.CreateModel(
            name='buyer_complaint_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Buyer Order Complaint Categories',
            },
        ),
        migrations.CreateModel(
            name='buyer_complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Buyer Order Complaints',
            },
        ),
        migrations.CreateModel(
            name='buyer_general_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Buyer General Order Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='buyer_general_feedback_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Buyer General Order Feedback Categories',
            },
        ),
        migrations.CreateModel(
            name='complaint_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buyer.buyer_complaints')),
            ],
            options={
                'verbose_name_plural': 'Complaint Responses',
            },
        ),
    ]
