# Generated by Django 2.2.10 on 2020-03-11 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyer', '0002_auto_20200310_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample_request',
            options={'verbose_name_plural': 'Sample Requests (Enquiry)'},
        ),
        migrations.RenameField(
            model_name='sample_request',
            old_name='order',
            new_name='enquiry',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='sample_follow_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('sample_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buyer.sample_request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sample Requests (Enquiry) Follow-Up',
            },
        ),
    ]
