# Generated by Django 2.2 on 2020-04-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20200416_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='country_code',
            field=models.CharField(default=91, max_length=3),
            preserve_default=False,
        ),
    ]
