# Generated by Django 2.2.10 on 2020-03-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_auto_20200311_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer_complaint_categories',
            options={'verbose_name_plural': 'Buyer Order Complaint Categories'},
        ),
        migrations.AlterModelOptions(
            name='buyer_complaints',
            options={'verbose_name_plural': 'Buyer Order Complaints'},
        ),
    ]
