# Generated by Django 2.2.10 on 2020-04-05 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_auto_20200311_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample_request',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='sample_request',
            name='enquiry',
        ),
        migrations.DeleteModel(
            name='sample_follow_up',
        ),
        migrations.DeleteModel(
            name='sample_request',
        ),
    ]
