# Generated by Django 2.2.10 on 2020-03-11 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20200310_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent_complaints',
            old_name='order',
            new_name='enquiry',
        ),
        migrations.AddField(
            model_name='agent',
            name='commission',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
