# Generated by Django 2.2.10 on 2020-03-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_auto_20200311_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
