# Generated by Django 2.2.10 on 2020-03-10 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cts', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('consignee', models.CharField(max_length=100)),
                ('addr1', models.CharField(max_length=100)),
                ('addr2', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.FileField(upload_to='')),
                ('products', models.ManyToManyField(to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='supplier_complaint_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Supplier Order Complaint Categories',
            },
        ),
        migrations.CreateModel(
            name='supplier_feedback_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Supplier Order Feedback Categories',
            },
        ),
        migrations.CreateModel(
            name='supplierquotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.FloatField()),
                ('price_kg', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('gst', models.FloatField()),
                ('freight', models.FloatField()),
                ('discount', models.FloatField()),
                ('total_amount_payable', models.FloatField()),
                ('document', models.FileField(upload_to='')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier')),
            ],
            options={
                'verbose_name_plural': 'Supplier Quotations',
            },
        ),
        migrations.CreateModel(
            name='supplier_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier_feedback_categories')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier')),
            ],
            options={
                'verbose_name_plural': 'Supplier Order Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='supplier_complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.order')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier_feedback_categories')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier')),
            ],
            options={
                'verbose_name_plural': 'Supplier Order Complaints',
            },
        ),
        migrations.CreateModel(
            name='complaint_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier_complaints')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_complaint_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Complaint Responses',
            },
        ),
    ]
