# Generated by Django 2.2.10 on 2020-03-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20200311_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='consignee',
        ),
    ]
